source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
    pod 'youtube-ios-player-helper', '~> 0.1.4'
end

target 'PlayVideo' do
    shared_pods
end
